### ISSUE TITLE
Make compatible with symfony/css-selector v4.x

### ISSUE THREAD

**Issue by amenk** [lstrojny/phpunit-dom-assertions#12]

**Comment by maderlock** [comment]
Yes please! This is currently stopping me using this with the latest version of Magento, which uses v4.2.4 of symfony/css-selector.

**Comment by lstrojny** [comment]
If anybody has time to file a pull request, that would be very welcome

**Comment by lasselehtinen** [comment]
Pull request created.

**Comment by Slamdunk** [comment]
Closed by https://github.com/lstrojny/phpunit-dom-assertions/pull/16
