### ISSUE TITLE
PHPunit 8 compatibility?

### ISSUE THREAD

**Issue by keesvandieren** [lstrojny/phpunit-dom-assertions#14]
PHPunit 7 and 8 are not supported, Composer says PHPUnit version < 7 should be used.

See: https://packagist.org/packages/phpunit/phpunit-dom-assertions

**Comment by lstrojny** [comment]
Haven’t tested it yet but if you can, check it out and file a PR please.

**Comment by Slamdunk** [comment]
Close by https://github.com/lstrojny/phpunit-dom-assertions/pull/21
